checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - tests/*
  paths:
    - src/*

build:
  environment:
    php:
      version: 7.2
  dependencies:
    override:
      - 
        command: 'composer require --dev "symfony/symfony:3.4.*" --no-update'
      -
        command: 'composer update --no-interaction -vv --profile --no-progress'
        idle_timeout: 900
  # Run after dependencies
  project_setup:
    before:
      - mysql -e 'CREATE DATABASE liip;'

    override: []
    after: []
  tests:
    override:
      # in phpunit.xml.dist, tests annotated with "@group mysql" are
      # excluded, revert this
      -
        command: 'php ./vendor/bin/phpunit --coverage-clover=coverage-clover --exclude-group ""'
        coverage:
          file: 'coverage-clover'
          format: 'php-clover'
